### ISSUE TITLE
Support Storage app connection in ecodev-core

### ISSUE THREAD

**Issue by Olivier-Gabriel** [FR-PAR-ECOACT/ecodev-core#17]
**Is your feature request related to a problem? Please describe.**

It seems that the connection features to storage apps can be used in multiple apps 

Should we include this existing code in this module? Or is that the topic of the https://github.com/FR-PAR-ECOACT/ecodev-s3 library?

**Comment by tepelbaum** [comment]
Will be in ecodev cloud! :)
